export { AppKit, useAppKit, AppKitAuthed, type AppKitTheme, type AppKitProps } from "./AppKit";
export { useTheme, type ColorTokens, type ColorMode, type ThemeContextValue } from "./theme";
export type {
  ManyRowsAppKitError,
  ManyRowsAppKitErrorCode,
  ManyRowsAppKitReady,
  ManyRowsAppKitHandle,
  ManyRowsAppKitSnapshot,
  AppKitAccount,
  AppKitAppData,
  AppKitFeatureFlag,
  AppKitConfigValue,
  AppKitOrganization,
  AppKitOrganizationRole,
  AppKitOrganizationMember,
  AppKitOrganizationInvite,
  AppKitCreatedOrganization,
  AppKitOrgListParams,
  AppKitOrganizationMemberPage,
  AppKitOrganizationInvitePage,
  AppKitSession,
  AppKitPasskey,
  AppKitIdentity,
  AppKitUserField,
  AppKitReauthParams,
  AppKitTOTPSetup,
} from "./types";

// Convenience hooks
export {
  useUser,
  useRoles,
  usePermissions,
  usePermission,
  useRole,
  useFeatureFlags,
  useFeatureFlag,
  useConfig,
  useConfigValue,
  useToken,
  useAuthFetch,
  useUpdateProfile,
  useSetPassword,
  useIdentities,
  useDisconnectIdentity,
  useUserFields,
  useUpdateUserFields,
  useDeleteAccount,
  useRequestEmailChange,
  useVerifyEmailChange,
  useRequestReauthCode,
  useOrganization,
  useOrganizationList,
  useSetActiveOrganization,
  // Self-serve organization management
  useCreateOrganization,
  useRenameOrganization,
  useArchiveOrganization,
  useOrganizationMembers,
  useSetOrganizationMember,
  useRemoveOrganizationMember,
  useOrganizationInvites,
  useCreateOrganizationInvite,
  useRevokeOrganizationInvite,
  useSessions,
  useRevokeSession,
  useRevokeOtherSessions,
  usePasskeys,
  useRenamePasskey,
  useDeletePasskey,
  useRegisterPasskey,
  isPasskeyCancelled,
  PASSKEY_CANCELLED,
  isPasskeyAlreadyRegistered,
  PASSKEY_ALREADY_REGISTERED,
  useStartTOTPSetup,
  useEnableTOTP,
  useDisableTOTP,
  useRegenerateBackupCodes,
} from "./hooks";
export { isPasskeySupported } from "./webauthn";
