"""Typed Python client for the ManyRows server-to-server API."""

from .client import ManyRowsServer, ManyRowsServerError
from .models import (
    AuthLogEntry,
    AuthLogsPage,
    BatchUserResult,
    CheckPermissionResult,
    CreateUserResult,
    Delivery,
    DeliveryConfig,
    DeliveryConfigItem,
    DeliveryFlagItem,
    DeliveryFlags,
    Identity,
    MagicLinkResult,
    Passkey,
    Member,
    MembersList,
    PermissionSummary,
    RemoveUserResult,
    RoleSummary,
    ServerUser,
    Session,
    User,
    UserField,
    UserFieldValue,
    UserStatus,
)

__version__ = "0.1.0"

__all__ = [
    "ManyRowsServer",
    "ManyRowsServerError",
    "AuthLogEntry",
    "AuthLogsPage",
    "BatchUserResult",
    "CheckPermissionResult",
    "CreateUserResult",
    "Delivery",
    "DeliveryConfig",
    "DeliveryConfigItem",
    "DeliveryFlagItem",
    "DeliveryFlags",
    "Identity",
    "MagicLinkResult",
    "Passkey",
    "Member",
    "MembersList",
    "PermissionSummary",
    "RemoveUserResult",
    "RoleSummary",
    "ServerUser",
    "Session",
    "User",
    "UserField",
    "UserFieldValue",
    "UserStatus",
]
