-- +goose Up
-- Consolidated green-field schema. Squash of migrations 00001..00008
-- (no deployed instances to migrate). Generated by applying those 8
-- migrations to a clean Postgres 16 and dumping the result, then
-- verified byte-identical to that schema. Plain DDL only -- no goose
-- StatementBegin needed (matches the prior 00001 convention).

CREATE TABLE account_email_change_otps (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    new_email text NOT NULL,
    code_hash text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account_email_otps (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    code_hash text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account_password_reset_otps (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    code_hash text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE accounts (
    id uuid NOT NULL,
    email text NOT NULL,
    name text NOT NULL,
    validated_at timestamp with time zone,
    password_hash text,
    password_set_at timestamp with time zone,
    language character varying(10) DEFAULT 'en'::character varying,
    locked_until timestamp with time zone,
    totp_secret_encrypted bytea,
    totp_enabled_at timestamp with time zone,
    totp_backup_codes_encrypted bytea,
    last_totp_step bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE api_keys (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    app_id uuid,
    name text NOT NULL,
    prefix text NOT NULL,
    hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid NOT NULL
);

CREATE TABLE app_cors_origins (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    origin text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE app_ip_allowlist (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    ip_range text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE app_users (
    app_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    source character varying(20) NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    CONSTRAINT app_users_status_check CHECK ((status = ANY (ARRAY['active'::text, 'pending'::text, 'disabled'::text])))
);

CREATE TABLE apps (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    product_id uuid NOT NULL,
    type text NOT NULL,
    description text,
    enabled boolean DEFAULT false NOT NULL,
    allow_registration boolean DEFAULT false NOT NULL,
    default_role_id uuid,
    allowed_email_domains text[] DEFAULT '{}'::text[],
    primary_auth_method text DEFAULT 'password'::text NOT NULL,
    auth_method_google boolean DEFAULT true NOT NULL,
    google_oauth_client_id text,
    google_oauth_client_secret_encrypted bytea,
    auth_method_apple boolean DEFAULT false NOT NULL,
    apple_services_id text,
    apple_team_id text,
    apple_key_id text,
    apple_private_key_encrypted bytea,
    auth_method_microsoft boolean DEFAULT false NOT NULL,
    microsoft_client_id text,
    microsoft_client_secret_encrypted bytea,
    microsoft_tenant text DEFAULT 'common'::text NOT NULL,
    auth_method_github boolean DEFAULT false NOT NULL,
    github_client_id text,
    github_client_secret_encrypted bytea,
    webauthn_rpid text,
    require_2fa boolean DEFAULT false NOT NULL,
    allow_account_deletion boolean DEFAULT true NOT NULL,
    allow_email_change boolean DEFAULT false NOT NULL,
    password_min_length integer DEFAULT 8 NOT NULL,
    password_min_zxcvbn_score integer DEFAULT 2 NOT NULL,
    app_url text,
    session_ttl_minutes integer,
    idle_timeout_minutes integer,
    remember_me_ttl_minutes integer,
    access_token_ttl_minutes integer,
    max_sessions_per_user integer,
    cookie_domain text,
    transport_mode text DEFAULT 'local'::text NOT NULL,
    session_cookie_samesite text DEFAULT 'lax'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    auth_domain text,
    user_pool_id uuid NOT NULL,
    CONSTRAINT apps_password_min_length_check CHECK (((password_min_length >= 1) AND (password_min_length <= 256))),
    CONSTRAINT apps_password_min_zxcvbn_score_check CHECK (((password_min_zxcvbn_score >= 0) AND (password_min_zxcvbn_score <= 4))),
    CONSTRAINT apps_primary_auth_method_check CHECK ((primary_auth_method = ANY (ARRAY['password'::text, 'code'::text, 'magicLink'::text, 'none'::text]))),
    CONSTRAINT apps_session_cookie_samesite_check CHECK ((session_cookie_samesite = ANY (ARRAY['lax'::text, 'strict'::text]))),
    CONSTRAINT apps_transport_mode_check CHECK ((transport_mode = ANY (ARRAY['local'::text, 'cookie'::text]))),
    CONSTRAINT apps_type_check CHECK ((type = ANY (ARRAY['prod'::text, 'staging'::text, 'dev'::text])))
);

CREATE TABLE attempts (
    id uuid NOT NULL,
    purpose text NOT NULL,
    subject text NOT NULL,
    ip text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE auth_logs (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    app_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event text NOT NULL,
    method text,
    outcome text NOT NULL,
    failure_reason text,
    subject_user_id uuid,
    subject_account_id uuid,
    email_attempted text,
    actor_type text NOT NULL,
    actor_account_id uuid,
    actor_api_key_id uuid,
    actor_label text,
    ip inet,
    user_agent text,
    session_id uuid,
    request_id text,
    metadata jsonb,
    CONSTRAINT auth_logs_actor_type_check CHECK ((actor_type = ANY (ARRAY['self'::text, 'admin'::text, 'api_key'::text, 'system'::text]))),
    CONSTRAINT auth_logs_outcome_check CHECK ((outcome = ANY (ARRAY['success'::text, 'failed'::text])))
);

CREATE TABLE client_otp_codes (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    email_norm text NOT NULL,
    code_hash text NOT NULL,
    requested_ip text DEFAULT ''::text NOT NULL,
    requested_user_agent text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp with time zone,
    CONSTRAINT client_otp_codes_attempts_nonneg CHECK ((attempts >= 0)),
    CONSTRAINT client_otp_codes_expires_after_create CHECK ((expires_at > created_at))
);

CREATE TABLE client_refresh_tokens (
    id uuid NOT NULL,
    session_id uuid NOT NULL,
    token_hash text NOT NULL,
    dpop_jkt text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    rotated_at timestamp with time zone,
    revoked_at timestamp with time zone,
    replaced_by_id uuid,
    user_agent text DEFAULT ''::text NOT NULL,
    ip text DEFAULT ''::text NOT NULL,
    CONSTRAINT client_refresh_tokens_expires_after_create CHECK ((expires_at > created_at))
);

CREATE TABLE client_sessions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    app_id uuid,
    remember_me boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text DEFAULT ''::text NOT NULL,
    ip text DEFAULT ''::text NOT NULL
);

CREATE TABLE config_keys (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    key text NOT NULL,
    exposure text NOT NULL,
    value_type text DEFAULT 'string'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_account_id uuid NOT NULL,
    CONSTRAINT config_keys_exposure_check CHECK ((exposure = ANY (ARRAY['public'::text, 'private'::text, 'secret'::text]))),
    CONSTRAINT config_keys_status_check CHECK ((status = ANY (ARRAY['active'::text, 'archived'::text]))),
    CONSTRAINT config_keys_value_type_check CHECK ((value_type = ANY (ARRAY['string'::text, 'int'::text, 'decimal'::text, 'bool'::text, 'string[]'::text, 'int[]'::text, 'decimal[]'::text, 'bool[]'::text, 'json'::text])))
);

CREATE TABLE config_values (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    app_id uuid NOT NULL,
    config_key_id uuid NOT NULL,
    value_json jsonb,
    value_encrypted bytea,
    updated_at timestamp with time zone NOT NULL,
    updated_by_account_id uuid NOT NULL,
    CONSTRAINT config_values_one_value_check CHECK ((((value_json IS NOT NULL) AND (value_encrypted IS NULL)) OR ((value_json IS NULL) AND (value_encrypted IS NOT NULL))))
);

CREATE TABLE dpop_replay (
    jkt text NOT NULL,
    jti text NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE email_change_requests (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    app_id uuid NOT NULL,
    new_email text NOT NULL,
    code_hash text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE feature_flag_overrides (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    app_id uuid NOT NULL,
    feature_flag_id uuid NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    role_ids uuid[] DEFAULT '{}'::uuid[],
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by_account_id uuid NOT NULL
);

CREATE TABLE feature_flags (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    key text NOT NULL,
    description text,
    scope text DEFAULT 'server'::text NOT NULL,
    default_enabled boolean DEFAULT false NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_account_id uuid NOT NULL,
    CONSTRAINT feature_flags_scope_check CHECK ((scope = ANY (ARRAY['server'::text, 'client'::text])))
);

CREATE TABLE magic_links (
    id uuid NOT NULL,
    purpose text NOT NULL,
    email text NOT NULL,
    token_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone
);

CREATE TABLE oauth_states (
    jti uuid NOT NULL,
    app_id uuid NOT NULL,
    provider text NOT NULL,
    opener_origin text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    prelogin_session_id uuid,
    CONSTRAINT oauth_states_provider_check CHECK ((provider = ANY (ARRAY['google'::text, 'apple'::text, 'microsoft'::text, 'github'::text])))
);

CREATE TABLE permissions (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE products (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_account_id uuid
);

CREATE TABLE role_permissions (
    id uuid NOT NULL,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE roles (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE sessions (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    token_id uuid NOT NULL,
    token_secret_hash bytea NOT NULL,
    token_prefix text,
    user_agent text,
    ip text
);

CREATE TABLE system_secrets (
    name text NOT NULL,
    value text NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE team_invites (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    email text NOT NULL,
    invited_by uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    accepted_at timestamp with time zone,
    CONSTRAINT team_invites_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text])))
);

CREATE TABLE user_field_values (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    user_field_id uuid NOT NULL,
    value_json jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid NOT NULL
);

CREATE TABLE user_fields (
    id uuid NOT NULL,
    key text NOT NULL,
    value_type text DEFAULT 'string'::text NOT NULL,
    visibility text DEFAULT 'server'::text NOT NULL,
    user_editable boolean DEFAULT false NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_account_id uuid NOT NULL,
    user_pool_id uuid NOT NULL,
    CONSTRAINT user_fields_status_check CHECK ((status = ANY (ARRAY['active'::text, 'archived'::text]))),
    CONSTRAINT user_fields_value_type_check CHECK ((value_type = ANY (ARRAY['string'::text, 'bool'::text, 'date'::text]))),
    CONSTRAINT user_fields_visibility_check CHECK ((visibility = ANY (ARRAY['client'::text, 'server'::text])))
);

CREATE TABLE user_identities (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    user_pool_id uuid NOT NULL,
    provider character varying(20) NOT NULL,
    provider_subject text NOT NULL,
    provider_email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE user_passkeys (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    user_id uuid NOT NULL,
    credential_id bytea NOT NULL,
    public_key bytea NOT NULL,
    sign_count bigint DEFAULT 0 NOT NULL,
    transports character varying(40)[] DEFAULT '{}'::character varying[] NOT NULL,
    aaguid uuid,
    backup_eligible boolean DEFAULT false NOT NULL,
    backup_state boolean DEFAULT false NOT NULL,
    name character varying(80),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone
);

CREATE TABLE user_permissions (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    user_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE user_pools (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE user_roles (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE user_tags (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    user_id uuid NOT NULL,
    tag character varying(40) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE users (
    id uuid NOT NULL,
    email text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    email_verified_at timestamp with time zone,
    password_hash text,
    password_set_at timestamp with time zone,
    source character varying(20) DEFAULT 'invited'::character varying NOT NULL,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    totp_secret_encrypted bytea,
    totp_enabled_at timestamp with time zone,
    totp_backup_codes_encrypted bytea,
    last_totp_step bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_pool_id uuid NOT NULL
);

CREATE TABLE webauthn_challenges (
    id uuid NOT NULL,
    app_id uuid NOT NULL,
    user_id uuid,
    purpose character varying(20) NOT NULL,
    challenge bytea NOT NULL,
    session_data jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT webauthn_challenges_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['register'::character varying, 'login'::character varying])::text[])))
);

CREATE TABLE webhook_deliveries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    webhook_id uuid NOT NULL,
    event text NOT NULL,
    payload jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    status_code integer,
    response_body text,
    attempts integer DEFAULT 0 NOT NULL,
    next_retry_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT webhook_deliveries_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])))
);

CREATE TABLE webhooks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid NOT NULL,
    app_id uuid NOT NULL,
    url text NOT NULL,
    secret text NOT NULL,
    events text[] DEFAULT '{}'::text[] NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid NOT NULL,
    CONSTRAINT webhooks_status_check CHECK ((status = ANY (ARRAY['active'::text, 'disabled'::text])))
);

CREATE TABLE workspace_admins (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    account_id uuid NOT NULL,
    role text DEFAULT 'admin'::text NOT NULL,
    added_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE workspace_encryption_keys (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    public_key_jwk jsonb NOT NULL,
    fingerprint text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid
);

CREATE TABLE workspace_smtp_config (
    workspace_id uuid NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    host text DEFAULT ''::text NOT NULL,
    port integer DEFAULT 587 NOT NULL,
    username text DEFAULT ''::text NOT NULL,
    password_encrypted bytea,
    from_email text DEFAULT ''::text NOT NULL,
    from_name text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE workspaces (
    id uuid NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    cookie_domain text,
    setup_checklist_dismissed_at timestamp with time zone,
    setup_test_email_sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    google_oauth_client_id text
);

ALTER TABLE ONLY account_email_change_otps
    ADD CONSTRAINT account_email_change_otps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY account_email_otps
    ADD CONSTRAINT account_email_otps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY account_password_reset_otps
    ADD CONSTRAINT account_password_reset_otps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT accounts_email_key UNIQUE (email);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY app_cors_origins
    ADD CONSTRAINT app_cors_origins_pkey PRIMARY KEY (id);

ALTER TABLE ONLY app_ip_allowlist
    ADD CONSTRAINT app_ip_allowlist_pkey PRIMARY KEY (id);

ALTER TABLE ONLY app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (app_id, user_id);

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_product_type_unique UNIQUE (product_id, type);

ALTER TABLE ONLY attempts
    ADD CONSTRAINT attempts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client_otp_codes
    ADD CONSTRAINT client_otp_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client_refresh_tokens
    ADD CONSTRAINT client_refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client_sessions
    ADD CONSTRAINT client_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY config_keys
    ADD CONSTRAINT config_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY config_keys
    ADD CONSTRAINT config_keys_product_key_unique UNIQUE (product_id, key);

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_app_key_unique UNIQUE (app_id, config_key_id);

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_pkey PRIMARY KEY (id);

ALTER TABLE ONLY dpop_replay
    ADD CONSTRAINT dpop_replay_pkey PRIMARY KEY (jkt, jti);

ALTER TABLE ONLY email_change_requests
    ADD CONSTRAINT email_change_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY feature_flag_overrides
    ADD CONSTRAINT feature_flag_overrides_pkey PRIMARY KEY (id);

ALTER TABLE ONLY feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY magic_links
    ADD CONSTRAINT magic_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY magic_links
    ADD CONSTRAINT magic_links_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY oauth_states
    ADD CONSTRAINT oauth_states_pkey PRIMARY KEY (jti);

ALTER TABLE ONLY permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY permissions
    ADD CONSTRAINT permissions_project_id_slug_key UNIQUE (product_id, slug);

ALTER TABLE ONLY products
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY role_permissions
    ADD CONSTRAINT role_permissions_role_id_permission_id_key UNIQUE (role_id, permission_id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_project_id_slug_key UNIQUE (product_id, slug);

ALTER TABLE ONLY sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sessions
    ADD CONSTRAINT sessions_token_id_key UNIQUE (token_id);

ALTER TABLE ONLY system_secrets
    ADD CONSTRAINT system_secrets_pkey PRIMARY KEY (name);

ALTER TABLE ONLY team_invites
    ADD CONSTRAINT team_invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_field_values
    ADD CONSTRAINT user_field_values_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_field_values
    ADD CONSTRAINT user_field_values_user_field_unique UNIQUE (user_id, user_field_id);

ALTER TABLE ONLY user_fields
    ADD CONSTRAINT user_fields_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_fields
    ADD CONSTRAINT user_fields_pool_key_unique UNIQUE (user_pool_id, key);

ALTER TABLE ONLY user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_passkeys
    ADD CONSTRAINT user_passkeys_app_credential_unique UNIQUE (app_id, credential_id);

ALTER TABLE ONLY user_passkeys
    ADD CONSTRAINT user_passkeys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_permissions
    ADD CONSTRAINT user_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_pools
    ADD CONSTRAINT user_pools_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_pools
    ADD CONSTRAINT user_pools_workspace_id_name_key UNIQUE (workspace_id, name);

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_tags
    ADD CONSTRAINT user_tags_app_user_tag_unique UNIQUE (app_id, user_id, tag);

ALTER TABLE ONLY user_tags
    ADD CONSTRAINT user_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY webauthn_challenges
    ADD CONSTRAINT webauthn_challenges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY webhooks
    ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY workspace_admins
    ADD CONSTRAINT workspace_admins_pkey PRIMARY KEY (id);

ALTER TABLE ONLY workspace_admins
    ADD CONSTRAINT workspace_admins_workspace_id_account_id_key UNIQUE (workspace_id, account_id);

ALTER TABLE ONLY workspace_encryption_keys
    ADD CONSTRAINT workspace_encryption_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY workspace_encryption_keys
    ADD CONSTRAINT workspace_encryption_keys_workspace_unique UNIQUE (workspace_id);

ALTER TABLE ONLY workspace_smtp_config
    ADD CONSTRAINT workspace_smtp_config_pkey PRIMARY KEY (workspace_id);

ALTER TABLE ONLY workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY workspaces
    ADD CONSTRAINT workspaces_slug_key UNIQUE (slug);

CREATE UNIQUE INDEX api_keys_workspace_id_prefix_uq ON api_keys USING btree (workspace_id, prefix);

CREATE INDEX auth_logs_app_created_idx ON auth_logs USING btree (app_id, created_at DESC) WHERE (app_id IS NOT NULL);

CREATE INDEX auth_logs_email_attempted_idx ON auth_logs USING btree (workspace_id, lower(email_attempted), created_at DESC);

CREATE INDEX auth_logs_event_idx ON auth_logs USING btree (workspace_id, event, created_at DESC);

CREATE INDEX auth_logs_outcome_idx ON auth_logs USING btree (workspace_id, outcome, created_at DESC);

CREATE INDEX auth_logs_session_idx ON auth_logs USING btree (session_id) WHERE (session_id IS NOT NULL);

CREATE INDEX auth_logs_subject_account_idx ON auth_logs USING btree (subject_account_id, created_at DESC) WHERE (subject_account_id IS NOT NULL);

CREATE INDEX auth_logs_subject_user_idx ON auth_logs USING btree (subject_user_id, created_at DESC) WHERE (subject_user_id IS NOT NULL);

CREATE INDEX auth_logs_ws_created_idx ON auth_logs USING btree (workspace_id, created_at DESC);

CREATE INDEX idx_account_email_change_otps_account_id ON account_email_change_otps USING btree (account_id);

CREATE INDEX idx_account_email_change_otps_expires_at ON account_email_change_otps USING btree (expires_at);

CREATE INDEX idx_account_email_change_otps_pending_email ON account_email_change_otps USING btree (lower(new_email), expires_at) WHERE (used_at IS NULL);

CREATE INDEX idx_account_email_change_otps_used_at ON account_email_change_otps USING btree (used_at);

CREATE INDEX idx_account_email_otps_account_id ON account_email_otps USING btree (account_id);

CREATE INDEX idx_account_email_otps_expires_at ON account_email_otps USING btree (expires_at);

CREATE INDEX idx_account_email_otps_used_at ON account_email_otps USING btree (used_at);

CREATE INDEX idx_account_password_reset_otps_account_id ON account_password_reset_otps USING btree (account_id);

CREATE INDEX idx_account_password_reset_otps_expires_at ON account_password_reset_otps USING btree (expires_at);

CREATE INDEX idx_account_password_reset_otps_used_at ON account_password_reset_otps USING btree (used_at);

CREATE INDEX idx_accounts_created_at ON accounts USING btree (created_at);

CREATE UNIQUE INDEX idx_accounts_email_lower ON accounts USING btree (lower(email));

CREATE INDEX idx_accounts_password_set_at ON accounts USING btree (password_set_at);

CREATE INDEX idx_api_keys_app_id ON api_keys USING btree (app_id);

CREATE INDEX idx_api_keys_workspace ON api_keys USING btree (workspace_id);

CREATE INDEX idx_app_cors_origins_app ON app_cors_origins USING btree (app_id);

CREATE INDEX idx_app_ip_allowlist_app ON app_ip_allowlist USING btree (app_id);

CREATE INDEX idx_app_users_app_status ON app_users USING btree (app_id, status);

CREATE INDEX idx_app_users_user ON app_users USING btree (user_id);

CREATE INDEX idx_apps_product_id ON apps USING btree (product_id);

CREATE INDEX idx_apps_user_pool ON apps USING btree (user_pool_id);

CREATE INDEX idx_apps_workspace_id ON apps USING btree (workspace_id);

CREATE INDEX idx_attempts_purpose_ip_created ON attempts USING btree (purpose, ip, created_at DESC);

CREATE INDEX idx_attempts_purpose_subject_created ON attempts USING btree (purpose, subject, created_at DESC);

CREATE INDEX idx_client_otp_codes_app_email_created ON client_otp_codes USING btree (app_id, email_norm, created_at DESC);

CREATE INDEX idx_client_otp_codes_unused_lookup ON client_otp_codes USING btree (app_id, email_norm, created_at DESC) WHERE (used_at IS NULL);

CREATE INDEX idx_client_refresh_tokens_expires ON client_refresh_tokens USING btree (expires_at);

CREATE UNIQUE INDEX idx_client_refresh_tokens_hash ON client_refresh_tokens USING btree (token_hash);

CREATE INDEX idx_client_refresh_tokens_session_active ON client_refresh_tokens USING btree (session_id, expires_at DESC) WHERE ((revoked_at IS NULL) AND (rotated_at IS NULL));

CREATE INDEX idx_client_sessions_app ON client_sessions USING btree (app_id);

CREATE INDEX idx_client_sessions_user ON client_sessions USING btree (user_id, expires_at);

CREATE INDEX idx_config_keys_product ON config_keys USING btree (product_id);

CREATE INDEX idx_config_keys_product_exposure ON config_keys USING btree (product_id, exposure);

CREATE INDEX idx_config_keys_product_status ON config_keys USING btree (product_id, status);

CREATE INDEX idx_config_values_app ON config_values USING btree (app_id);

CREATE INDEX idx_config_values_key ON config_values USING btree (config_key_id);

CREATE INDEX idx_config_values_product ON config_values USING btree (product_id);

CREATE INDEX idx_config_values_product_app ON config_values USING btree (product_id, app_id);

CREATE INDEX idx_dpop_replay_expires_at ON dpop_replay USING btree (expires_at);

CREATE INDEX idx_feature_flag_overrides_app ON feature_flag_overrides USING btree (app_id);

CREATE INDEX idx_feature_flag_overrides_flag ON feature_flag_overrides USING btree (feature_flag_id);

CREATE INDEX idx_feature_flag_overrides_product ON feature_flag_overrides USING btree (product_id);

CREATE INDEX idx_feature_flag_overrides_updated_by ON feature_flag_overrides USING btree (updated_by_account_id);

CREATE INDEX idx_feature_flags_created_by ON feature_flags USING btree (created_by_account_id);

CREATE INDEX idx_feature_flags_product ON feature_flags USING btree (product_id);

CREATE INDEX idx_feature_flags_product_scope ON feature_flags USING btree (product_id, scope);

CREATE INDEX idx_magic_links_email ON magic_links USING btree (lower(email));

CREATE INDEX idx_magic_links_expires ON magic_links USING btree (expires_at);

CREATE INDEX idx_permissions_product ON permissions USING btree (product_id);

CREATE INDEX idx_permissions_product_slug ON permissions USING btree (product_id, slug);

CREATE INDEX idx_products_workspace ON products USING btree (workspace_id);

CREATE INDEX idx_products_workspace_name ON products USING btree (workspace_id, name);

CREATE INDEX idx_role_permissions_permission ON role_permissions USING btree (permission_id);

CREATE INDEX idx_role_permissions_role ON role_permissions USING btree (role_id);

CREATE INDEX idx_roles_product ON roles USING btree (product_id);

CREATE INDEX idx_roles_product_slug ON roles USING btree (product_id, slug);

CREATE INDEX idx_sessions_account_id ON sessions USING btree (account_id);

CREATE INDEX idx_sessions_expires_at ON sessions USING btree (expires_at);

CREATE INDEX idx_sessions_token_id ON sessions USING btree (token_id);

CREATE INDEX idx_team_invites_email ON team_invites USING btree (lower(email)) WHERE (status = 'pending'::text);

CREATE INDEX idx_team_invites_workspace ON team_invites USING btree (workspace_id);

CREATE INDEX idx_user_field_values_field ON user_field_values USING btree (user_field_id);

CREATE INDEX idx_user_field_values_user ON user_field_values USING btree (user_id);

CREATE INDEX idx_user_fields_pool ON user_fields USING btree (user_pool_id);

CREATE INDEX idx_user_fields_pool_status ON user_fields USING btree (user_pool_id, status);

CREATE INDEX idx_user_identities_user ON user_identities USING btree (user_id);

CREATE INDEX idx_user_passkeys_app_user ON user_passkeys USING btree (app_id, user_id);

CREATE INDEX idx_user_permissions_user ON user_permissions USING btree (user_id);

CREATE INDEX idx_user_pools_workspace ON user_pools USING btree (workspace_id);

CREATE INDEX idx_user_roles_app_user ON user_roles USING btree (app_id, user_id);

CREATE INDEX idx_user_roles_role ON user_roles USING btree (role_id);

CREATE INDEX idx_user_roles_user ON user_roles USING btree (user_id);

CREATE INDEX idx_user_tags_app_tag ON user_tags USING btree (app_id, tag);

CREATE INDEX idx_user_tags_app_user ON user_tags USING btree (app_id, user_id);

CREATE INDEX idx_users_email ON users USING btree (lower(email));

CREATE INDEX idx_webauthn_challenges_expires ON webauthn_challenges USING btree (expires_at);

CREATE INDEX idx_webhook_deliveries_retry ON webhook_deliveries USING btree (status, next_retry_at);

CREATE INDEX idx_webhook_deliveries_webhook ON webhook_deliveries USING btree (webhook_id);

CREATE INDEX idx_webhooks_app_id ON webhooks USING btree (app_id);

CREATE INDEX idx_webhooks_product ON webhooks USING btree (product_id);

CREATE INDEX idx_workspaces_created_at ON workspaces USING btree (created_at);

CREATE INDEX idx_workspaces_created_by ON workspaces USING btree (created_by);

CREATE INDEX oauth_states_expires_idx ON oauth_states USING btree (expires_at);

CREATE UNIQUE INDEX uq_api_keys_prefix ON api_keys USING btree (prefix);

CREATE UNIQUE INDEX uq_app_cors_origins ON app_cors_origins USING btree (app_id, origin);

CREATE UNIQUE INDEX uq_app_ip_allowlist ON app_ip_allowlist USING btree (app_id, ip_range);

CREATE UNIQUE INDEX uq_email_change_requests_user ON email_change_requests USING btree (user_id);

CREATE UNIQUE INDEX uq_feature_flag_overrides_flag_app ON feature_flag_overrides USING btree (feature_flag_id, app_id);

CREATE UNIQUE INDEX uq_feature_flags_product_key ON feature_flags USING btree (product_id, key);

CREATE UNIQUE INDEX uq_team_invites_pending ON team_invites USING btree (workspace_id, lower(email)) WHERE (status = 'pending'::text);

CREATE UNIQUE INDEX user_identities_pool_provider_subject_uniq ON user_identities USING btree (user_pool_id, provider, provider_subject);

CREATE UNIQUE INDEX user_identities_user_provider_uniq ON user_identities USING btree (user_id, provider);

CREATE UNIQUE INDEX users_email_user_pool_uniq ON users USING btree (lower(email), user_pool_id);

CREATE INDEX users_user_pool_idx ON users USING btree (user_pool_id);

CREATE UNIQUE INDEX ux_user_permissions ON user_permissions USING btree (app_id, user_id, permission_id);

CREATE UNIQUE INDEX ux_user_roles ON user_roles USING btree (app_id, user_id, role_id);

CREATE INDEX workspace_encryption_keys_workspace_id_idx ON workspace_encryption_keys USING btree (workspace_id);

ALTER TABLE ONLY account_email_change_otps
    ADD CONSTRAINT account_email_change_otps_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY account_email_otps
    ADD CONSTRAINT account_email_otps_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY account_password_reset_otps
    ADD CONSTRAINT account_password_reset_otps_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY api_keys
    ADD CONSTRAINT api_keys_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY api_keys
    ADD CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY api_keys
    ADD CONSTRAINT api_keys_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY app_cors_origins
    ADD CONSTRAINT app_cors_origins_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY app_ip_allowlist
    ADD CONSTRAINT app_ip_allowlist_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY app_users
    ADD CONSTRAINT app_users_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY app_users
    ADD CONSTRAINT app_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_default_role_id_fkey FOREIGN KEY (default_role_id) REFERENCES roles(id) ON DELETE SET NULL;

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_user_pool_id_fkey FOREIGN KEY (user_pool_id) REFERENCES user_pools(id) ON DELETE RESTRICT;

ALTER TABLE ONLY apps
    ADD CONSTRAINT apps_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_actor_account_id_fkey FOREIGN KEY (actor_account_id) REFERENCES accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_actor_api_key_id_fkey FOREIGN KEY (actor_api_key_id) REFERENCES api_keys(id) ON DELETE SET NULL;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_subject_account_id_fkey FOREIGN KEY (subject_account_id) REFERENCES accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_subject_user_id_fkey FOREIGN KEY (subject_user_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE ONLY auth_logs
    ADD CONSTRAINT auth_logs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT;

ALTER TABLE ONLY client_otp_codes
    ADD CONSTRAINT client_otp_codes_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY client_refresh_tokens
    ADD CONSTRAINT client_refresh_tokens_replaced_by_id_fkey FOREIGN KEY (replaced_by_id) REFERENCES client_refresh_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY client_refresh_tokens
    ADD CONSTRAINT client_refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES client_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY client_sessions
    ADD CONSTRAINT client_sessions_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY client_sessions
    ADD CONSTRAINT client_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_keys
    ADD CONSTRAINT config_keys_created_by_account_id_fkey FOREIGN KEY (created_by_account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_keys
    ADD CONSTRAINT config_keys_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_config_key_id_fkey FOREIGN KEY (config_key_id) REFERENCES config_keys(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY config_values
    ADD CONSTRAINT config_values_updated_by_account_id_fkey FOREIGN KEY (updated_by_account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY email_change_requests
    ADD CONSTRAINT email_change_requests_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY email_change_requests
    ADD CONSTRAINT email_change_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flag_overrides
    ADD CONSTRAINT feature_flag_overrides_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flag_overrides
    ADD CONSTRAINT feature_flag_overrides_feature_flag_id_fkey FOREIGN KEY (feature_flag_id) REFERENCES feature_flags(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flag_overrides
    ADD CONSTRAINT feature_flag_overrides_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flag_overrides
    ADD CONSTRAINT feature_flag_overrides_updated_by_account_id_fkey FOREIGN KEY (updated_by_account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flags
    ADD CONSTRAINT feature_flags_created_by_account_id_fkey FOREIGN KEY (created_by_account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY feature_flags
    ADD CONSTRAINT feature_flags_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY permissions
    ADD CONSTRAINT permissions_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY products
    ADD CONSTRAINT projects_created_by_account_id_fkey FOREIGN KEY (created_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY products
    ADD CONSTRAINT projects_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE;

ALTER TABLE ONLY role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY sessions
    ADD CONSTRAINT sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY team_invites
    ADD CONSTRAINT team_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY team_invites
    ADD CONSTRAINT team_invites_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_field_values
    ADD CONSTRAINT user_field_values_user_field_id_fkey FOREIGN KEY (user_field_id) REFERENCES user_fields(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_field_values
    ADD CONSTRAINT user_field_values_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_fields
    ADD CONSTRAINT user_fields_created_by_account_id_fkey FOREIGN KEY (created_by_account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_fields
    ADD CONSTRAINT user_fields_user_pool_id_fkey FOREIGN KEY (user_pool_id) REFERENCES user_pools(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_identities
    ADD CONSTRAINT user_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_identities
    ADD CONSTRAINT user_identities_user_pool_id_fkey FOREIGN KEY (user_pool_id) REFERENCES user_pools(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_passkeys
    ADD CONSTRAINT user_passkeys_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_passkeys
    ADD CONSTRAINT user_passkeys_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_permissions
    ADD CONSTRAINT user_permissions_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_permissions
    ADD CONSTRAINT user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_permissions
    ADD CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_pools
    ADD CONSTRAINT user_pools_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_tags
    ADD CONSTRAINT user_tags_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_tags
    ADD CONSTRAINT user_tags_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY users
    ADD CONSTRAINT users_user_pool_id_fkey FOREIGN KEY (user_pool_id) REFERENCES user_pools(id) ON DELETE CASCADE;

ALTER TABLE ONLY webauthn_challenges
    ADD CONSTRAINT webauthn_challenges_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY webauthn_challenges
    ADD CONSTRAINT webauthn_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE;

ALTER TABLE ONLY webhooks
    ADD CONSTRAINT webhooks_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;

ALTER TABLE ONLY webhooks
    ADD CONSTRAINT webhooks_created_by_fkey FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY webhooks
    ADD CONSTRAINT webhooks_project_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

ALTER TABLE ONLY workspace_admins
    ADD CONSTRAINT workspace_admins_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY workspace_admins
    ADD CONSTRAINT workspace_admins_added_by_fkey FOREIGN KEY (added_by) REFERENCES accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY workspace_admins
    ADD CONSTRAINT workspace_admins_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY workspace_encryption_keys
    ADD CONSTRAINT workspace_encryption_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE SET NULL;

ALTER TABLE ONLY workspace_encryption_keys
    ADD CONSTRAINT workspace_encryption_keys_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY workspace_smtp_config
    ADD CONSTRAINT workspace_smtp_config_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY workspaces
    ADD CONSTRAINT workspaces_created_by_fkey FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE SET NULL;


-- +goose Down
drop table if exists account_email_change_otps cascade;
drop table if exists account_email_otps cascade;
drop table if exists account_password_reset_otps cascade;
drop table if exists accounts cascade;
drop table if exists api_keys cascade;
drop table if exists app_cors_origins cascade;
drop table if exists app_ip_allowlist cascade;
drop table if exists app_users cascade;
drop table if exists apps cascade;
drop table if exists attempts cascade;
drop table if exists auth_logs cascade;
drop table if exists client_otp_codes cascade;
drop table if exists client_refresh_tokens cascade;
drop table if exists client_sessions cascade;
drop table if exists config_keys cascade;
drop table if exists config_values cascade;
drop table if exists dpop_replay cascade;
drop table if exists email_change_requests cascade;
drop table if exists feature_flag_overrides cascade;
drop table if exists feature_flags cascade;
drop table if exists magic_links cascade;
drop table if exists oauth_states cascade;
drop table if exists permissions cascade;
drop table if exists products cascade;
drop table if exists role_permissions cascade;
drop table if exists roles cascade;
drop table if exists sessions cascade;
drop table if exists system_secrets cascade;
drop table if exists team_invites cascade;
drop table if exists user_field_values cascade;
drop table if exists user_fields cascade;
drop table if exists user_identities cascade;
drop table if exists user_passkeys cascade;
drop table if exists user_permissions cascade;
drop table if exists user_pools cascade;
drop table if exists user_roles cascade;
drop table if exists user_tags cascade;
drop table if exists users cascade;
drop table if exists webauthn_challenges cascade;
drop table if exists webhook_deliveries cascade;
drop table if exists webhooks cascade;
drop table if exists workspace_admins cascade;
drop table if exists workspace_encryption_keys cascade;
drop table if exists workspace_smtp_config cascade;
drop table if exists workspaces cascade;
